name: Flutter Web Docker CI

on:
  push:
    branches:
      - 'main' 
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' 
          channel: 'stable' 

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release 

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}cyberbara_team_case:latest . \
            --build-arg BUILD_DATE=$(date +%Y-%m-%dT%H:%M:%SZ)

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/cyberbara_team_case:latest
